version: '3.7'

services:
  
  server:
    # image: efenstakes/Noty:latest
    build: .
    container_name: noty-server
    ports:
      - '80:5000'
    restart: always
    depends_on:
      - db

  db:
    image: mongo
    container_name: noty-db
    volumes:
      - noty-db-data:/data/db

volumes:
  noty-db-data:
